### ISSUE TITLE
scss variables

### ISSUE THREAD

**Issue by szkrd** [szkrd/recess-sorter#1]
Scss variables are reordered, but why? Is this a bug? Does gonzales identify these items properly?

Example rule:
```scss
.vars {
    $width: 300px;
    position: fixed;
    top: 100px;
    left: 50%;
    width: $width;
    margin-left: -$width / 2;
    background-color: #fff;
}
```
