### ISSUE TITLE
fallback properties for unsopperted browser are moved around

### ISSUE THREAD

**Issue by szkrd** [szkrd/recess-sorter#2]
```scss
.item {
	hyphens: auto;
	line-height: 1.5;
	word-break: break-all;
	word-break: break-word;
	word-wrap: break-word;
	overflow-wrap: break-word;
}
```

word-break should stay in place, but now it's moved away:

```scss
.item {
	hyphens: auto;
	line-height: 1.5;
	word-break: break-all;
	word-wrap: break-word;
	word-break: break-word; // <-- !!!
	overflow-wrap: break-word;
}
```
